### PR TITLE
Refactor allo-isolate to make it cleaner

### PR DESCRIPTION
**Pull request by fzyzcjy**
Hi thanks for the lib! I am trying to refactor it to make it cleaner. Things that I have done can be seen in the messages of each commit.

Possibly related: @jerel @shekohex

### CODE REVIEW

**Comment by fzyzcjy** [comment]
@shekohex Seems that "2 workflows awaiting approval". May I get the approval?

**Comment by shekohex** [comment]
Try `cargo +nightly fmt`.

**Comment by fzyzcjy** [comment]
@shekohex done

**Review by shekohex — APPROVED** [review]
LGTM!

Thank you.

**Pull request merged**
