### PR TITLE
Fix bug that `u32`'s IntoDart will make the value completely wrong

### PR DESCRIPTION
**Pull request by fzyzcjy**
Please refer to https://github.com/fzyzcjy/flutter_rust_bridge/issues/234 for details.

### CODE REVIEW

**Comment by shekohex** [comment]
Thanks for the fix looks good to me, could we write a quick unit test for that? to make sure it is working?

Somewhere near here? Like a new function here to test big numbers and return them back and assert the result is the same.

**Comment by fzyzcjy** [comment]
> Somewhere near here? Like a new function here

hmm where is "here"?

**Comment by shekohex** [comment]
> > Somewhere near here? Like a new function here
> 
> hmm where is "here"?

Oh sorry forgot to mention the file hahaha, there in the [containers.rs](https://github.com/sunshine-protocol/allo-isolate/blob/master/test/containers.rs)

**Comment by fzyzcjy** [comment]
ok

**Comment by fzyzcjy** [comment]
done

**Comment by shekohex** [comment]
Perfect!
Thank you, will publish a new version shortly.

**Comment by fzyzcjy** [comment]
You are welcome! Looking forward to it

**Comment by shekohex** [comment]
Published and included in v0.1.12 🎉

**Comment by fzyzcjy** [comment]
🎉

**Pull request merged**
