### PR TITLE
Fix/doc chrono

### PR DESCRIPTION
**Pull request by Roms1383**
While implementing it on `flutter_rust_bridge` I discovered some mistake in the docs and recommendations that I wrote earlier, so here are the fixes :)

### CODE REVIEW

**Comment by Roms1383** [comment]
Little issue with cargo fmt nightly, it totally break the code examples in the docs.

**Comment by shekohex** [comment]
Yea, would you like to update the github actions files to use rustfmt and clippy from the stable channel? and try again?

**Comment by Roms1383** [comment]
Sure, let me look into it

**Comment by Roms1383** [comment]
Apparently it's ok too to simply switch `rustfmt` to `stable`.

**Comment by shekohex** [comment]
Thank you!

**Pull request merged**
